[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/clientes"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

